[package]
name = "git_drive"
version = "0.2.0"
authors = ["Paul Horn <developer@knutwalker.de>"]
description = "Support for switching git authors and co-authors"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/knutwalker/git-drive"
default-run = "git-drive"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.2", default-features = false, features = ["cargo", "color", "std", "suggestions"] }
color-eyre = { version = "0.5.7", default-features = false, features = ["issue-url"] }
console = "0.13.0"
dialoguer = "0.7.1"
directories = "3.0.1"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"

[profile.dev.package.backtrace]
opt-level = 3

[[bin]]
name = "git-drive"
path = "src/main.rs"
