[package]
name = "git_drive"
version = "0.2.0"
authors = ["Paul Horn <developer@knutwalker.de>"]
description = "Support for switching git authors and co-authors"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/knutwalker/git-drive"
default-run = "git-drive"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = { git = "https://github.com/knutwalker/color-eyre", branch = "no-backtrace", default-features = false, features = ["issue-url"] }
console = "0.13.0"
dialoguer = "0.7.1"
directories = "3.0.1"
nanoserde = "0.1.20"
pico-args = "0.3.4"

[profile.release]
lto = "thin"
incremental = true

[[bin]]
name = "git-drive"
path = "src/main.rs"
