[package]
name = "git_drive"
version = "0.2.0"
authors = ["Paul Horn <developer@knutwalker.de>"]
description = "Support for switching git authors and co-authors"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/knutwalker/git-drive"
default-run = "git-drive"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.0"
directories = "4.0.1"
nanoserde = "0.1.29"
once_cell = "1.10.0"

[dependencies.clap]
version = "3.1.6"
default-features = false
features = ["derive", "std"]

[dependencies.color-eyre]
version = "0.6.1"
default-features = false
features = ["issue-url"]

[dependencies.dialoguer]
version = "0.10.0"
default-features = false
features = ["password"]

[profile.release]
lto = "thin"
incremental = false

[[bin]]
name = "git-drive"
path = "src/main.rs"
