name: releases

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macOS-latest
            target: x86_64-apple-darwin
            binary_postfix: ''
            upx_args: --best
            strip: true
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_postfix: ''
            upx_args: --best --lzma
            strip: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_postfix: '.exe'
            upx_args: -9
            strip: false
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.7
    steps:
      - uses: actions/checkout@v2
        if: startsWith(github.ref, 'refs/tags/')
      - uses: actions-rs/toolchain@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build release binaries
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          command: build
          args: --release --all-features --target=${{ matrix.target }}
      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file: target/${{ matrix.target }}/release/git-drive${{ matrix.binary_postfix }}
          args: ${{ matrix.upx_args }}
          strip: ${{ matrix.strip }}
      - name: Packaging binary
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf git-drive-${{ matrix.target }}.tar.gz git-drive${{ matrix.binary_postfix }}
          if [[ ${{ runner.os }} == 'Windows' ]]; then
            certutil -hashfile git-drive-${{ matrix.target }}.tar.gz sha256 | grep -E [A-Fa-f0-9]{64} > git-drive-${{ matrix.target }}.sha256
          else
            shasum -a 256 git-drive-${{ matrix.target }}.tar.gz > git-drive-${{ matrix.target }}.sha256
          fi
      - name: Releasing assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/git-drive-${{ matrix.target }}.tar.gz
            target/${{ matrix.target }}/release/git-drive-${{ matrix.target }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
